GET http://localhost:8000/breeds?limit=10&page=56&paginate=false
Content-Type: application/json

{
    "uniqueName": "chow_chow",
    "url": "https://en.wikipedia.org/wiki/Chow_Chow",
    "creationType": "original",
    "name": "Chow Chow"
}
